# Generated by Django 4.2.7 on 2023-11-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('qtd_quartos', models.IntegerField()),
                ('qtd_banheiro', models.IntegerField()),
                ('valor', models.FloatField()),
            ],
        ),
    ]
