# Generated by Django 4.2.7 on 2023-11-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_anuncio_descricao_anuncio_endereco_anuncio_tamanho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='url_imagem',
            field=models.TextField(blank=True, default=None),
        ),
    ]
